services:
  - type: web
    name: saas-deals
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y ./google-chrome-stable_current_amd64.deb
      CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
      wget https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip
      unzip chromedriver-linux64.zip
      mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
      chmod +x /usr/bin/chromedriver
      pip install -r requirements.txt

    startCommand: python main.py
