name: run-bot

on:
  schedule:
    - cron: "0 */6 * * *"   # Ejecuta cada 6 horas
  workflow_dispatch:        # Permite ejecutarlo manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python main.py
